---
brew_cask_packages:
  - 'google-chrome'
  - 'caffeine'
  - 'adoptopenjdk8'
  - 'android-studio'
  - 'android-sdk'
  - 'iterm2'
  - 'emacs'
  - 'postman'
  - 'spotify'
  - 'proxyman'
brew_packages:
  - 'git'
  - 'pyenv'
  - 'python3'
  - 'rbenv'
  - 'ruby-build'
  - 'git-extras'
  - 'nano'
  - 'bash-git-prompt'
  - 'gradle'
  - 'pyenv'
  - 'jq'
  - 'htop'
  - 'ncdu'
  - 'diff-so-fancy'
brew_taps:
  - 'homebrew/cask-versions'
  
android_sdk_build_tools: 28.0.3
android_sdk_versions: 
# Example:
  - android-28

android_sdk_system_images: 
# Example:
# - system-images;android-28;google_apis;x86
  - system-images;android-28;google_apis;x86

# Example:
# - name: API_28
#   image: system-images;android-28;google_apis;x86
#   skin: Nexus 5X
#   sdcard: 1024M  
android_sdk_emulators:
- name: emulator_api_28
  image: system-images;android-28;google_apis;x86
  skin: Nexus 5X
  sdcard: 1024M

install_homebrew_if_missing: true

upgrade_homebrew_packages: false

# iOS
configure_xcode: yes

macos_sleep_options:
  - systemsetup -setsleep Never
  - systemsetup -setharddisksleep Never
  - systemsetup -setcomputersleep Never
    
macos_animation_options:
  - defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false
  - defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
  - defaults write com.apple.dock expose-animation-duration -int 0
  - defaults write com.apple.dock launchanim -bool false

macos_software_autoupdates:
  - softwareupdate --schedule off

xcode_version: 12.4

apple_id: []
apple_password: []

ruby_version: 2.7.2
  
python_version: 3.7.3
